-- script that displays all the cities in California
-- since we cannot tell the state_id for California, we have to use a sub-query to generate it
-- We select the cities related to the state_id (Clifornia) generated by the sub-query
SELECT id, name FROM cities
	WHERE state_id = (
		SELECT id FROM states
			WHERE name = 'California'
		)
	ORDER BY id ASC;
